apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name:  seeker-som2-poi-map-app-dev
  annotations:
    argocd/app-name:  seeker-som2-poi-map-app-dev
    backstage.io/kubernetes-id:  seeker-som2-poi-map-app
    backstage.io/kubernetes-namespace:  seeker-som2
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/ seeker-som2-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/ seeker-som2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/ seeker-som2/deployments/ seeker-som2-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/ seeker-som2-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http:// seeker-som2-poi-map-app- seeker-som2.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/seeker-som"
  system: workshop-system- seeker-som2
  consumesApis:
    - gateway-api- seeker-som2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system- seeker-som2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/seeker-som"
